name: "SPA"
version: "3.9"
services:
    nginx:
        image: nginx:alpine
        ports:
        - "80:80"
        volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf

    db:
      image: postgres:alpine
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

    frontend:
      build: SPA-Frontend
      env_file:
        - SPA-Frontend/.env
      depends_on:
        - backend

    backend:
      build: SPA-Backend
      env_file:
        - SPA-Backend/.env
      depends_on:
        - db